### ISSUE TITLE
CPU问题

### ISSUE THREAD

**Issue by minushuang** [FangChengRu/STDC-seg_Demo#1]
Hi，请问下，这个代码在cpu上怎么跑呢？我用您的inference代码在cpu机器上跑（MAC），报cuda环境的错误。在代码`TDC-Seg-master/modules/functions.py` 18行处`extra_cuda_cflags=["--expt-extended-lambda"])`
 
报错信息
`raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

**Comment by FangChengRu** [comment]
Maybe you didn't chage net.cuda when you load model.

Try that change net.cuda:
```
device = torch.device("cpu")
net.to(device)
```
